[package]
name = "kicad-allegro"
version = "0.1.0"
authors = ["Jeremy Soller <jeremy@system76.com>"]
edition = "2018"

[build-dependencies]
gl_generator = "0.10"

[dependencies]
csv = "1.1"
glutin = "0.19"
natord = "1.0"
serde = { version = "1.0", features = ["derive"] }
